version: "3.3"
    
services:
  nginx:
    image: nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "443:443"
      - "80:80"
      - "8080:443"
    restart: always
    environment:
      - NGINX_HOST=wordpress.local
      - NGINX_PORT=80
    links:
      - wordpress
    extra_hosts:
      - "host.docker.internal:host-gateway"

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./www/:/var/www/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  db:
    image: mariadb:10.5.8
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 33061:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wordpress_data:/var/www/html
      - ./config/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "8081:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress 
      WORDPRESS_DB_NAME: wordpress
    links: 
      - db

  wpcli:
    image: wordpress:cli
    depends_on:
      - db
      - wordpress
    volumes:
      - ./wordpress_data:/var/www/html
    user: xfs
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wpdb